In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.4


In [3]:
arr1=np.array([11,22,33,44,55])
print("The array is: ",arr1)

The array is:  [11 22 33 44 55]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
arr2=np.array((77,88,99,100))
print(arr2)
print(type(arr2))

[ 77  88  99 100]
<class 'numpy.ndarray'>


In [7]:
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
arr4=np.array(["hello","hi","bye","go"])
print(arr4)

['hello' 'hi' 'bye' 'go']


In [5]:
print(arr4[0],arr4[1],arr4[2],arr4[3])

hello hi bye go


In [6]:
print(arr4.dtype)

<U5


In [7]:
print(type(arr4[0]))

<class 'numpy.str_'>


In [8]:
arr7=np.array(["hello",{1,2,3},[56,43],88,90,"bye"])
print(arr7)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

In [9]:
arr8=np.array([10, 20,30,40],complex)
print(arr8)

[10.+0.j 20.+0.j 30.+0.j 40.+0.j]


In [12]:
arr9=np.array([10, 20,30,40],float,ndmin=3)
print(arr9)

[[[10. 20. 30. 40.]]]


In [14]:
arr10=np.arange(1,50,2,complex)
print(arr10)

[ 1.+0.j  3.+0.j  5.+0.j  7.+0.j  9.+0.j 11.+0.j 13.+0.j 15.+0.j 17.+0.j
 19.+0.j 21.+0.j 23.+0.j 25.+0.j 27.+0.j 29.+0.j 31.+0.j 33.+0.j 35.+0.j
 37.+0.j 39.+0.j 41.+0.j 43.+0.j 45.+0.j 47.+0.j 49.+0.j]


In [15]:
arr11=np.linspace(1,20,5)
print(arr11)

[ 1.    5.75 10.5  15.25 20.  ]


In [18]:
arr12=np.array([[1,2,3],[10,20,30]])
print(arr12.max(axis=0))
print(arr12.max(axis=1))
print(arr12.min(axis=0))
print(arr12.min(axis=1))
print(arr12.sum(axis=0))
print(arr12.sum(axis=1))

[10 20 30]
[ 3 30]
[1 2 3]
[ 1 10]
[11 22 33]
[ 6 60]


In [19]:
print(np.sqrt(arr12))
print(np.std(arr12))
print(np.mean(arr12))
print(np.mean(arr12,axis=0))
print(np.mean(arr12,axis=1))

[[1.         1.41421356 1.73205081]
 [3.16227766 4.47213595 5.47722558]]
10.708252269472673
11.0
[ 5.5 11.  16.5]
[ 2. 20.]


In [21]:
print(arr12)
arr13=np.array([[4,5,6],[8,9,10]])
print(arr13)
print(arr12+arr13)
print(arr13-arr12)
print(arr12*arr13)
print(arr13/arr12)

[[ 1  2  3]
 [10 20 30]]
[[ 4  5  6]
 [ 8  9 10]]
[[ 5  7  9]
 [18 29 40]]
[[  3   3   3]
 [ -2 -11 -20]]
[[  4  10  18]
 [ 80 180 300]]
[[4.         2.5        2.        ]
 [0.8        0.45       0.33333333]]


In [26]:
arr14=np.empty((3,2),dtype=int,order='F')
print(arr14)

[[  4  80]
 [ 10 180]
 [ 18 300]]


In [32]:
arr15=np.zeros((3,4),dtype=complex,order='C')
print(arr15)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [35]:
for row in arr14:
    print(row)

[ 4 80]
[ 10 180]
[ 18 300]


In [43]:
arr16=np.array([[[1,2,3],[2,3,4]],[[4,5,6],[5,6,7]],[[6,7,8],[7,8,9]]])
for row in arr16:
    print(row)
    print("\n")

for row in arr16:
    for i in row:
        print(i)
        print("\n")

for row in arr16:
    for i in row:
        for j in i:
            print(j)
        print("\n")

[[1 2 3]
 [2 3 4]]


[[4 5 6]
 [5 6 7]]


[[6 7 8]
 [7 8 9]]


[1 2 3]


[2 3 4]


[4 5 6]


[5 6 7]


[6 7 8]


[7 8 9]


1
2
3


2
3
4


4
5
6


5
6
7


6
7
8


7
8
9




In [44]:
import pandas as pd
arr1=np.array(['h','e','l','l','o'])
series1=pd.Series(arr1)
print(series1)

0    h
1    e
2    l
3    l
4    o
dtype: object


In [46]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [47]:
list1=[['Hello','all'],[1,2],['a','b','c','d']]
df1=pd.DataFrame(list1)
print(df1)

       0    1     2     3
0  Hello  all  None  None
1      1    2  None  None
2      a    b     c     d


In [49]:
import pandas as pd
df1=pd.read_csv(r"C:/Users/Dell/Desktop/Databases_python ml/bestsellers.csv")
df1

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]